apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 0
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 0